version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
  pre_build:
    commands:
      - echo Starting pre_build phase...
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Starting build phase...
      - zip -r ../users.zip . 
  artifacts:
    files:
      - users.zip
